/*//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                    //
//    _____            .__ .__   .__                             _________  __              .___.__                   //
//   /  _  \    _____  |__||  |  |__|  ____   __ __  ______     /   _____/_/  |_  __ __   __| _/|__|  ____   ______   //
//  /  /_\  \  /     \ |  ||  |  |  | /  _ \ |  |  \/  ___/     \_____  \ \   __\|  |  \ / __ | |  | /  _ \ /  ___/   //
// /    |    \|  Y Y  \|  ||  |__|  |(  <_> )|  |  /\___ \      /        \ |  |  |  |  // /_/ | |  |(  <_> )\___ \    //
// \____|__  /|__|_|  /|__||____/|__| \____/ |____//____  >    /_______  / |__|  |____/ \____ | |__| \____//____  >   //
//         \/       \/                                  \/             \/                    \/                 \/    //
//                                                                                                                    //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//  Website:        http://www.amilious.com         Unity Asset Store: https://assetstore.unity.com/publishers/62511  //
//  Discord Server: https://discord.gg/SNqyDWu            Copyright© Amilious since 2022                              //                    
//  This code is part of an asset on the unity asset store. If you did not get this from the asset store you are not  //
//  using it legally. Check the asset store or join the discord for the license that applies for this script.         //
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////*/

using UnityEngine;
using Amilious.Core.Extensions;

namespace Amilious.Core.Editor.Extensions {
    
    /// <summary>
    /// This class is used to add methods to the <see cref="GUIStyleState"/> class.
    /// </summary>
    public static class GUIStyleStateExtensions {
        
        #region Public Methods /////////////////////////////////////////////////////////////////////////////////////////
        
        /// <summary>
        /// This method is used to replace the background with a texture generated by the given color.
        /// </summary>
        /// <param name="state">The state that you want to set a background color for.</param>
        /// <param name="color">The color that you want to set the background to.</param>
        public static void SetBackGroundColor(this GUIStyleState state, Color color) {
            state.background = color.MakeTexture(2, 2);
        }

        /// <summary>
        /// This method is used to replace the background with a texture generated by the given color.
        /// </summary>
        /// <param name="state">The state that you want to set a background color for.</param>
        /// <param name="htmlCode">The color that you want to set the background to.</param>
        public static void SetBackgroundColor(this GUIStyleState state, string htmlCode) {
            if(!htmlCode.StartsWith("#")) htmlCode = $"#{htmlCode}";
            ColorUtility.TryParseHtmlString(htmlCode, out var color);
            state.SetBackGroundColor(color);
        }
        
        #endregion /////////////////////////////////////////////////////////////////////////////////////////////////////
        
    }
    
}